on:
  push:
    branches: [ "main" ]

name: 🚀 Deploy website on push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Generate build
        run: npm run build

  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    needs: [build]
    steps:

      - name: Clone repository
          uses: actions/checkout@v3

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: bringittocode.org
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          exclude: |
            dont.md
            **/node_modules/**
            **/.github/**
            **/.git/**
            **/pages/**
            styles
            postcss.config.js
            README.md
            .gitignore
            .eslintrc.json